---
title: "Data Analysis Showcase"
description: "A group of projects dedicated to the quantitative analysis of political data I did while studying module GOV300."
output: distill::distill_article
---

## Projects

### [Electoral Participation in the UK](project1.html)

An analysis of UK constituency-level election data to examine turnout, electorate size, and inequalities in political representation.This project examines whether voters are equally represented across UK constituencies.

### [Measuring Trust in the Central Bank](project2.html)

This project examines how trust in the central bank can be measured using survey data from the Q37 battery. It focuses on key issues in quantitative research, including missing data, reliability, and scale construction.

### [Who Isn’t Voting?](project3.html)

An analysis of a voter turnout across UK constituencies, with a particular focus on inequalities in political participation. By analysing patterns of turnout and non-voting, it highlights how variations in participation—especially across different social and geographic contexts—can shape electoral outcomes and raise important questions about representation in democratic systems.

---

[← Back to Home](index.html)